- name: Conditions Demo
  hosts: iosxe1*,junos1*
  gather_facts: true
  tasks:
    - name: Change Description on GE1
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "Hello_GE1"
      when: ansible_network_os == "cisco.ios.ios"

    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        text: "Any Damn Thing 11"
        state: present
      when: ansible_network_os == "cisco.ios.ios"

    - name: Enable the netconf service on port 830
      junipernetworks.junos.junos_netconf:
        netconf_port: 830
        state: present
      when: ansible_network_os == "junipernetworks.junos.junos"
      vars:
        ansible_connection: ansible.netcommon.network_cli

    - name: Configure a MOTD banner
      junipernetworks.junos.junos_banner:
        banner: motd
        text: This is an Ansible-managed node
        state: present
      when: ansible_network_os == "junipernetworks.junos.junos"

    - name: Disable the netconf service on port 830
      vars:
        ansible_connection: ansible.netcommon.network_cli
      junipernetworks.junos.junos_netconf:
        netconf_port: 830
        state: absent
      when: ansible_network_os == "junipernetworks.junos.junos"
