- name: force_handlers Dependency Task
  hosts: iosxe1*
  gather_facts: false
  force_handlers: true
  tasks:
    - name: Change Description
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "Hello_GE1"
      notify:
        - Description Changed
        - IOS Settings Saved

    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: loginn
        text: "Any Damn Thing 11"
        state: present
      notify:
        - IOS Settings Saved
        - Banner Changed

    - name: Test reachability to 198.51.100.251
      cisco.ios.ios_ping:
        dest: 172.25.250.24
      notify:
        - Nobody Intersted

  handlers:
    - name: Nobody Intersted
      ansible.builtin.debug:
        msg: "Nobody Intersted in ME"

    - name: Banner Changed
      ansible.builtin.debug:
        msg: "Success Banner Changed"

    - name: Description Changed
      ansible.builtin.debug:
        msg: "Success Description Changed"

    - name: IOS Settings Saved
      cisco.ios.ios_config:
        save_when: always
