galaxy_info:
  author: Denislav Iliev
  description: Learning Roles
  company: SAP Inc.

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies:
  # - role: another
  - role: info_role
